[build]
  command = "echo 'MCP Server - No build required'"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.12"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/sse"
  to = "/.netlify/functions/mcp-server"
  status = 200

[[redirects]]
  from = "/messages/*"
  to = "/.netlify/functions/mcp-server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  command = "python src/crawl4ai_mcp_server/main.py"
  port = 8051
